# Generated by Django 3.2.8 on 2021-11-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name']},
        ),
    ]
