# Generated by Django 3.2.9 on 2022-10-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='buyPrice',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
