# Generated by Django 3.2.9 on 2021-12-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-datetime']},
        ),
    ]
