# Generated by Django 3.2.9 on 2021-12-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['firstName', 'fatherName', 'secondName']},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-invoice__datetime']},
        ),
    ]
