# Generated by Django 3.2.9 on 2021-12-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgeries', '0001_initial'),
        ('drugs', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('motherName', models.CharField(max_length=15)),
                ('fatherName', models.CharField(max_length=15)),
                ('secondName', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15, null=True)),
                ('occupation', models.CharField(max_length=15, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('attendantName', models.CharField(max_length=50, null=True)),
                ('attendantPhone', models.CharField(max_length=10, null=True)),
                ('attendantAdderss', models.CharField(max_length=100, null=True)),
                ('room', models.IntegerField(null=True)),
                ('therapy', models.CharField(max_length=30, null=True)),
                ('acceptID', models.IntegerField()),
                ('enter', models.DateTimeField()),
                ('out', models.DateTimeField(null=True)),
                ('birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('family', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PatientSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeonCosts', models.PositiveIntegerField(null=True)),
                ('assistantCosts', models.PositiveIntegerField(null=True)),
                ('anestheticCosts', models.PositiveIntegerField(null=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('price', models.PositiveIntegerField()),
                ('surgeonPaided', models.BooleanField(default=False)),
                ('assistantPaided', models.BooleanField(default=False)),
                ('anestheticPaided', models.BooleanField(default=False)),
                ('anesthetic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeriesAsAnesthetic', to='doctors.doctor')),
                ('assistant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeriesAsAssistant', to='doctors.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgerisAsSergeon', to='doctors.doctor')),
                ('surgery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surgeries.surgery')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(null=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.drug')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.employee')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patientCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeryRom', models.PositiveIntegerField(null=True)),
                ('residence', models.PositiveIntegerField(null=True)),
                ('serums', models.PositiveIntegerField(null=True)),
                ('arches', models.PositiveIntegerField(null=True)),
                ('threads', models.PositiveIntegerField(null=True)),
                ('plastic', models.PositiveIntegerField(null=True)),
                ('laboratory', models.PositiveIntegerField(null=True)),
                ('rays', models.PositiveIntegerField(null=True)),
                ('ECG', models.PositiveIntegerField(null=True)),
                ('resuscitate', models.PositiveIntegerField(null=True)),
                ('monitor', models.PositiveIntegerField(null=True)),
                ('echo', models.PositiveIntegerField(null=True)),
                ('axial', models.PositiveIntegerField(null=True)),
                ('incubator', models.PositiveIntegerField(null=True)),
                ('gypsum', models.PositiveIntegerField(null=True)),
                ('plates', models.PositiveIntegerField(null=True)),
                ('bandages', models.PositiveIntegerField(null=True)),
                ('intensiveCare', models.PositiveIntegerField(null=True)),
                ('service', models.PositiveIntegerField(null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('paided', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='consults',
            field=models.ManyToManyField(through='patients.PatientConsult', to='doctors.Doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.doctor'),
        ),
    ]
