# Generated by Django 3.2.9 on 2022-01-11 13:17

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='enter',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='out',
        ),
        migrations.AddField(
            model_name='patient',
            name='enterDate',
            field=models.DateField(default=datetime.datetime.now().date()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='enterTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='outDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='outTime',
            field=models.TimeField(null=True),
        ),
    ]
