# Generated by Django 3.2.8 on 2021-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDrugs',
            new_name='PatientDrug',
        ),
        migrations.AlterField(
            model_name='patient',
            name='attendantName',
            field=models.CharField(max_length=50),
        ),
    ]
