# Generated by Django 3.2.9 on 2022-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20220111_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdrug',
            name='discrete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
