# Generated by Django 3.2.9 on 2021-12-05 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_invoice_options'),
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdrug',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdrug',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.employee'),
        ),
    ]
