# Generated by Django 3.2.8 on 2021-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20211103_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdrug',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
