# Generated by Django 3.2.9 on 2022-01-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientdrug_discrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
