# Generated by Django 3.2.9 on 2021-12-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20211205_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdrug',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
