# Generated by Django 3.2.8 on 2021-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientdrug_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsurgery',
            name='anestheticCosts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='assistantCosts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientsurgery',
            name='surgeonCosts',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
