# Generated by Django 3.2.8 on 2021-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20211106_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsult',
            name='paided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientsurgery',
            name='paided',
            field=models.BooleanField(default=False),
        ),
    ]
