# Generated by Django 3.2.9 on 2022-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsurgery',
            name='primaryDuration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
