# Generated by Django 3.2.9 on 2022-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientsurgery_primaryduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsurgery',
            name='QHAP',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
