# Generated by Django 3.2.8 on 2021-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20211110_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsurgery',
            old_name='paided',
            new_name='anestheticPaided',
        ),
        migrations.AddField(
            model_name='patientsurgery',
            name='assistantPaided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientsurgery',
            name='surgeonPaided',
            field=models.BooleanField(default=False),
        ),
    ]
