# Generated by Django 3.2.8 on 2021-11-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20211117_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcosts',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='patients.patient'),
        ),
    ]
