# Generated by Django 3.2.8 on 2021-11-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_options'),
        ('patients', '0009_alter_patientdrug_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdrug',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs.drug'),
        ),
        migrations.AlterField(
            model_name='patientdrug',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='patients.patient'),
        ),
    ]
