# Generated by Django 3.2.9 on 2021-12-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('secondName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('specialzation', models.CharField(max_length=50)),
                ('surgeon', models.BooleanField()),
                ('assistant', models.BooleanField()),
                ('anesthetic', models.BooleanField()),
            ],
            options={
                'ordering': ['firstName', 'fatherName', 'secondName'],
            },
        ),
    ]
