# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1105, 662)
        self.serverStatus = QtWidgets.QLabel(Form)
        self.serverStatus.setGeometry(QtCore.QRect(700, 30, 390, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serverStatus.sizePolicy().hasHeightForWidth())
        self.serverStatus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.serverStatus.setFont(font)
        self.serverStatus.setText("")
        self.serverStatus.setObjectName("serverStatus")
        self.serverButton = QtWidgets.QPushButton(Form)
        self.serverButton.setGeometry(QtCore.QRect(550, 50, 93, 28))
        self.serverButton.setObjectName("serverButton")
        self.serverButtonBack = QtWidgets.QPushButton(Form)
        self.serverButtonBack.setGeometry(QtCore.QRect(430, 50, 93, 28))
        self.serverButtonBack.setObjectName("serverButtonBack")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.serverButton.setText(_translate("Form", "تشغيل"))
        self.serverButtonBack.setText(_translate("Form", "تشغيل بالخلفية"))
