# Generated by Django 3.2.9 on 2021-11-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgeries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
