# Generated by Django 3.2.9 on 2022-10-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='buyPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
